### ISSUE TITLE
Dart 3 incompatible

### ISSUE THREAD

**Issue by rupeshs** [GAM3RG33K/flutter_settings_screens#118]
It would be better to make it flutter settings screen dart 3 compatible.
Thanks!

![image](https://github.com/GAM3RG33K/flutter_settings_screens/assets/3255994/46527175-26d6-44cf-be03-f1b1ca390343)

**Comment by mbfakourii** [comment]
@GAM3RG33K

**Comment by GAM3RG33K** [comment]
Closing this as the latest update, adds support for the Dart 3
