### ISSUE TITLE
Title sizes differ on SimpleSettings Widgets

### ISSUE THREAD

**Issue by zanesc** [GAM3RG33K/flutter_settings_screens#13]
I have a SwitchSettingsTile and a SliderSettingsTile set and they both have different title font sizes. It would be great if the title size remained the same or if there was a custom property to set them.

`SwitchSettingsTile(
    title: 'Sound Effects',
    settingKey: 'soundEffects',
    leading: Icon(Icons.audiotrack),
    onChange: (bool value) async {
    },
),
SliderSettingsTile(
    title: 'Sound Effect Volume',
    leading: Icon(Icons.audiotrack),
    settingKey: 'soundEffectVolume',
    defaultValue: 0.5,
    min: 0,
    max: 1,
    step: 0.01,
    onChange: (double value) async {
    },
),`

![Screenshot_20200618_200250_com apphoss allfourslime](https://user-images.githubusercontent.com/1435517/85083328-6758a300-b19f-11ea-8688-f16608ea641a.jpg)

**Comment by GAM3RG33K** [comment]
I have not seen such an issue before. I'll make sure to keep the text sizes consistent as much as possible. 
It would be great if you can just share the minimum code snippet which can reproduce the issue.
It would help me find out the root cause.

**Comment by GAM3RG33K** [comment]
@zanesc Can you try the example app in latest commit from [patch](https://github.com/GAM3RG33K/flutter_settings_screens/tree/patch-title-texsize-resize) branch.

You can modify the example app with your own settings page. If this doesn't resolve this issue let me know what went wrong. I'll fix this issue for sure.

**Comment by GAM3RG33K** [comment]
If everything went ok then I'll merge this fix in master and then give an update in plugin

**Comment by zanesc** [comment]
That patch branched fixed it. Thank you very much.
