### ISSUE TITLE
SwitchSettingsTile onChange not working if tap tile (tap switch button, working)

### ISSUE THREAD

**Issue by aztecrabbit** [GAM3RG33K/flutter_settings_screens#19]

**Comment by GAM3RG33K** [comment]
can you provide a small sample code/snippet through which this same issue can be reproduced?
Also please add some description as well to inform about any specific situations when you found this issue.

Thanks.

**Comment by GAM3RG33K** [comment]
closing this due to no response and description of the issue.

**Comment by hellochenwang** [comment]
I experience the same issue using the example code with flutter web.
