### ISSUE TITLE
Settings Widgets should be Type Generic

### ISSUE THREAD

**Issue by GAM3RG33K** [GAM3RG33K/flutter_settings_screens#2]
For example: 
`RadioPickerSettingsTile` assumes that the radio button values are only strings. hence requires only <String, String> map as values.

Or `SliderSettingsTile` requires only double value as step, max and min. however it is also possible that the range slide is used for 0-100% value without any decimal progress included.

what can be done is every settings widget takes a generic type as input.
For example: 

```dart
RadioPickerSettingsTile<int, String>(
  settingKey: KEY_WITH_INT_VALUE,
  title: 'Base for auto divergence',
  values: <int, String>{
    1: 'One',
    2: 'Two',
   },
  defaultKey: 2,
)
```

**Comment by FLAGLORD** [comment]
It would be nicer that values could take ENUM
