### ISSUE TITLE
SimpleSettingsTile title/subtitle fields don't align with other settings' widgets

### ISSUE THREAD

**Issue by msthoma** [GAM3RG33K/flutter_settings_screens#21]
Hello, I've just started using the library, and it's great! 

I noticed the following issue - the title/subtitle fields of SimpleSettingsTile don't align with other settings' widgets title/subtitle fields when no `leading` icon is provided to them. In the example below I added SimpleSettingsTile along with a CheckboxSettingsTile and a SwitchSettingsTile to show what I mean:

![Screenshot_20200904-144944](https://user-images.githubusercontent.com/29862068/92236834-e7e59080-eebe-11ea-8ae2-87dfaa12f0db.jpg)

Same screen below with Debug paint enabled:

![Screenshot_20200904-145023__01](https://user-images.githubusercontent.com/29862068/92237068-5f1b2480-eebf-11ea-8ef9-3d3908d79c14.jpg)

It seems there is an extra 4 or 8 pixel padding (marked with the arrow) at the beginning of CheckboxSettingsTile and SwitchSettingsTile, so their titles/subtitles don't align with those of SimpleSettingsTile. Is it possible to remove it? I tried to find where the extra padding is coming from but I couldn't find it. 

This is the code I used (btw I'm not using any custom theme if that matters, just ThemeData.dark()):

```
SettingsScreen(
  title: "Settings",
  children: [
    SimpleSettingsTile(
      title: "About",
      subtitle: "subtitle",
      onTap: () {},
    ),
    CheckboxSettingsTile(
      settingKey: 'key-setting-checkbox',
      title: 'Checkbox',
      subtitle: "subtitle",
    ),
    SwitchSettingsTile(
      settingKey: "switch-key",
      title: "Switch",
      subtitle: "subtitle",
    )
  ],
);
```

**Comment by msthoma** [comment]
Actually the lack of a leading icon seems not to be related, below I added an icon to all 3 and the extra padding is still there for  CheckboxSettingsTile and SwitchSettingsTile, causing the misalignment with SimpleSettingsTile.

![Screenshot_20200904-153741](https://user-images.githubusercontent.com/29862068/92240119-c38cb280-eec4-11ea-807a-a792763fb266.jpg)

**Comment by GAM3RG33K** [comment]
Thanks for this detailed analysis of the issue. I really appreciate you taking the time to gather this much information. I will look for this issue in code and will let you know if this change in padding is handled by the flutter framework or something which I made.

An additional note: 
I am happy that you like this library. You can always contribute any improvements or addition in this library via PR.

**Comment by GAM3RG33K** [comment]
@msthoma Hi, I found out the real reason behind this additional left side padding. It was due to the use of `SettingsConatiner` with a default value as 4.0 instead of 2.0. 

 I am making a few changes to handle many of the alignment related issues. Your overlay analysis really helped me a lot. thanks.

**Comment by msthoma** [comment]
Hello @GAM3RG33K, that's fantastic, thanks for the quick reply and fix! 

I found another small bug, and since it's alignment related, I won't open another issue for it (maybe you also caught it already with your fixes). When the subtitle is > 20 chars long, it changes the alignment of the tiles as shown below:

![Screenshot_20200907-102646](https://user-images.githubusercontent.com/29862068/92360554-abe84080-f0f5-11ea-96b9-87980ce8e02e.jpg)

I remember seeing such a check in the code somewhere the other day, I guess it's for making sure the subtitle can wrap to a 2nd line if necessary, but I can't find it again today. 

I'll definitely consider submitting a PR if I find something I can fix/improve in the future. Thanks again!

**Comment by msthoma** [comment]
Hi @GAM3RG33K! Just wanted to let you know that I got the chance to test your bugfixes today, and the issue is fully resolved. Thanks and hope you have a happy new year!

**Comment by GAM3RG33K** [comment]
That is awesome. Thanks for taking time. Happy new year to you too.
