### ISSUE TITLE
Can I use a ValueListenableBuilder with a settings key?

### ISSUE THREAD

**Issue by IanWorthington** [GAM3RG33K/flutter_settings_screens#37]
My apologies if this is a stupid question, but I'm a bit new around here and am struggling to see how this works.

If I currently have a ValueListenableBuilder widget listening on a global ValueNotifier, eg:

```
ValueListenableBuilder(
      valueListenable: globals.isDarkTheme2,   ... )
```

how do I correctly change this so it gets notified when the value associated with the settings key changes?

The SwitchSettingsTile I'm using is
```
                SwitchSettingsTile(
                title: "Dark Theme",
                settingKey: "key-darkTheme",
                leading: Icon(Icons.remove_red_eye_outlined),
                subtitle: "", // Empty string here displays label
                enabledLabel: "Enabled",
                disabledLabel: "Disabled",
                onChange: (value) {
                  debugPrint('darkTheme: $value');
                },
              )
```

and to capture it I'm trying variations on ValueChangeObserver, the most recent being the following (though it gives "type 'bool' is not a subtype of type 'String'", for reasons I haven't yet worked out.  I've tried other variations that build ok, but don't fire

```
    return ValueChangeObserver<String>(
      cacheKey: "key-darkTheme",
      defaultValue: "",
      builder: (BuildContext context, String value, child) {
        print("MyApp.vlb(isDarkTheme2).builder() called ");

        return MaterialApp(
       ...
      )
      },
    );
```

**Comment by GAM3RG33K** [comment]
@IanWorthington That is not the case right now. But it is a good suggestion. I'll look into it, maybe I can provide a way to notify of changes based on the key you want to listen to.

**Comment by IanWorthington** [comment]
> @IanWorthington That is not the case right now. But it is a good suggestion. I'll look into it, maybe I can provide a way to notify of changes based on the key you want to listen to.

Ok, thanks.  

What's the best way of monitoring a setting for changes then for now?  I can creating a shadow variable in the settings onChange() but what's the best way reload the saved setting on application restart?  Each one manually?

Can you give an example of what ValueChangeObserver<>() can be used for?  I'm sure it has some use!  Maybe it can help, somehow?

**Comment by IanWorthington** [comment]
Good news!  This DOES work right now.  I just had to debug how the variables were used -- differently than I had assumed --  and everything dropped into place.
