### ISSUE TITLE
rxdart update

### ISSUE THREAD

**Issue by domizilver** [GAM3RG33K/flutter_settings_screens#4]
any new update for the latest rxdart? thank you

**Comment by GAM3RG33K** [comment]
I am aware of the issue and I already have an update planned this weekend.

rxdart library itself is no longer needed.

The new update will be a re-developed version with new settings and more
advanced version of existing settings.

I hope the next update will resolve all your issues, as well as mine... 😂

Thanks and Regards,
Harshvardhan Joshi

**Comment by GAM3RG33K** [comment]
Please update to new version of the library. It is not using rxdart library anymore.
