### ISSUE TITLE
Use only the UI

### ISSUE THREAD

**Issue by Androz2091** [GAM3RG33K/flutter_settings_screens#43]
Hello,
I'm currently using [settings-ui](https://github.com/yako-dev/flutter-settings-ui) but the project is not really maintained. I only use it to simply the UI code of my project, do you think that I can use your project without using any CacheProvider and only simple onPress functions?

**Comment by GAM3RG33K** [comment]
If I understand correctly, then you don't need to implement `CacheProvider`. 
You can skip providing your version of cache provider to use the default one that uses shared preferences under the hood.

If you mean to only use the UI & not the underlying backend for settings, then I am afraid its not possible.

**Comment by Androz2091** [comment]
> If you mean to only use the UI & not the underlying backend for settings, then I am afraid its not possible.

Yes that's what I meant. All right thank you so I will wait for settings-ui to be released 👍
