### ISSUE TITLE
Null Safety Support

### ISSUE THREAD

**Issue by JohannesMilke** [GAM3RG33K/flutter_settings_screens#45]
Is Null Safety Support for this package planned?

**Comment by GAM3RG33K** [comment]
@JohannesMilke Hi, I have null safety port in my goals for next few updates.

**Comment by yom-ko** [comment]
Seconded. This is a great package but it's the only one that blocks migration to sound null safety for my app.

**Comment by GAM3RG33K** [comment]
Null safety migration #49 merged successfully & published as `v0.3.0-null-safety`. 

Though it is a prerelease version right now, to find & fix some quick bugs if any.
Soon it will be a stable one.
