### ISSUE TITLE
Why do Silders only increment by whole number when specified to do 0.1 steps?

### ISSUE THREAD

**Issue by Slenderic** [GAM3RG33K/flutter_settings_screens#48]
Hello, 
I've the problem that I want to have a slide bar that goes from 0 to 3.5 with steps of 0.1. However it won't do it.
1st if i set the max to 3.5 it goes shows 3.5 however it's not possible to slide it to the 3.5 and goes out of bound to 4.0
2nd the slider steps are shown as dots but when slid on the slider jumps to the closest whole number e.g. putting the slider on 2.6 it jumps to 3 even though there are dots between the two values.

Is there a chance to implement a setting to disable the dots like in the Slider class provided by Flutter by putting the division to null?

**Comment by GAM3RG33K** [comment]
Sorry for the delayed response.

Can you provide the code snippet of the Slider settings you have implemented?

Regarding the dots on the slider, I have tried to look for settings or properties to disable them but no success yet.

**Comment by Slenderic** [comment]
```
SliderSettingsTile(
                title: 'Custom Ratio',
                settingKey: 'key-custom-ratio-slider-2',
                defaultValue: 2.5,
                min: 1,
                max: 4.5,
                step: 0.1,
                leading: Icon(Icons.aspect_ratio),
                onChange: (value) {
                  debugPrint('\n===== on change =====\n'
                      'key-custom-ratio-slider-2: $value'
                      '\n==========\n');
                },
                onChangeStart: (value) {
                  debugPrint('\n===== on change start =====\n'
                      'key-custom-ratio-slider-2: $value'
                      '\n==========\n');
                },
                onChangeEnd: (value) {
                  debugPrint('\n===== on change end =====\n'
                      'key-custom-ratio-slider-2: $value'
                      '\n==========\n');
                },
              ),
```

**Comment by GAM3RG33K** [comment]
No worries, check with the new prerelease version. Please provide any feedback for this if you feel like it.
