### ISSUE TITLE
how to set CheckboxSettingsTile is checked ?

### ISSUE THREAD

**Issue by GitKyRep** [GAM3RG33K/flutter_settings_screens#50]

**Comment by GAM3RG33K** [comment]
Hi,
you can set `defaultValue` property as `true` to set the initial state of CheckboxSettingsTile as Checked.

You can check the documentation here: 
https://pub.dev/documentation/flutter_settings_screens/latest/flutter_settings_screens/CheckboxSettingsTile/defaultValue.html

Closing this as it is not a plugin's implementation issue but if you need more help with it, add a comment here.
