### ISSUE TITLE
SwitchSettingsTile does not have the same behavior when taping on the switch or on the tile

### ISSUE THREAD

**Issue by pascalwils** [GAM3RG33K/flutter_settings_screens#51]
Hi,

I found that taping on the SwitchSettingsTile does not called the onChange callback while taping on the switch call it. Whereas, the switch state is always changed.

When using the CheckboxSettingsTile, the behavior seems more coherent, the callback onChange is always called not depending on where you tap.

I think the correction is simple. Like in CheckboxSettingsTile, you should replace the line 721 of settings_widget.dart "onTap: () => onChanged(!value)," with "onTap: () => _onSwitchChange(context, !value, onChanged),".

What do you think of this correction ? If you are agree I can do a PR with this correction.

Pascal

**Comment by GAM3RG33K** [comment]
Sure, it makes sense. 
Please submit a PR if you can.

**Comment by GAM3RG33K** [comment]
Fixed by recent PR#52. Closing this now.
