### ISSUE TITLE
Question: how do you setCheck on a CheckboxSettingsTile?

### ISSUE THREAD

**Issue by amigax** [GAM3RG33K/flutter_settings_screens#54]
I want to check a CheckboxSettingsTile in code, but how ?

**Comment by GAM3RG33K** [comment]
I am not sure what the actual issue you are facing but after the latest plugin update [null safe version](https://pub.dev/packages/flutter_settings_screens/versions/0.3.1-null-safety), there are following ways to set a checkbox status:

1. If you are looking for setting it checked by default then try passing default argument as `true`
2. If you are trying to update checkbox state manually then try following:
```dart
await Settings.setValue<bool>(checkBoxSettingsKey, true, notify: true);
```

**Note**: `notify` is a new parameter added in this latest update, which updates the status of all widgets linked to a specific settings key.


If you think this resolves the issue then let me know so I can close this issue.

**Comment by GAM3RG33K** [comment]
Closing this issue for now. If you still face any issues please re-open this issue with some new information about it, so that I can resolve it.
