### ISSUE TITLE
please update to provider 6.0.0

### ISSUE THREAD

**Issue by jeffreyliu8** [GAM3RG33K/flutter_settings_screens#58]
please update to provider 6.0.0

**Comment by Pawelek55** [comment]
Update provider will be extremely helpful

**Comment by GAM3RG33K** [comment]
@jeffreyliu8  @Pawelek55  Thanks for pointing out this issue. But I am in no position to provide a release right away. I have seen that @Pawelek55 has made a fork with the same changes required, so I suggest you use that fork for the time being.

@Pawelek55 Please create a pull request for the same & I will merge the changes As soon as I am able to spare time for a release.

I really appreciate that you guys are using this library & taking time to file issues as well. Thank you so much for that.

**Comment by Pawelek55** [comment]
@GAM3RG33K Thanks for response. I made pull request, so if You will have time, please accept the change.

**Comment by GAM3RG33K** [comment]
Merged the pull request successfully. WIll try to provide the release ASAP. However it will still be a preview release, because there's zero code coverage as of now. Which I want to resolve first for the next major release.

Thank you for your contribution & I really appreciate it.
