### ISSUE TITLE
TextInputSettingsTile error , Working in iOS but error in Android debug 

### ISSUE THREAD

**Issue by rajesh2701** [GAM3RG33K/flutter_settings_screens#59]
"setState() or markNeedsBuild() called during build.
This AnimatedBuilder widget cannot be marked as needing to build because the framework is already in the process of building widgets.  A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was:
  AnimatedBuilder
The widget which was currently being built when the offending call was made was:
  ValueListenableBuilder<String>"

**Comment by GAM3RG33K** [comment]
can you provide sample code that reproduces the issue?
