### ISSUE TITLE
SimpleSettingsTile takes only SettingsScreen parameter

### ISSUE THREAD

**Issue by GAM3RG33K** [GAM3RG33K/flutter_settings_screens#7]
`SimpleSettingsTile` takes a `screen` parameter which allows only `SettingsScreen` value. Instead it should take any widget as input for screen. Even the parameter name `screen` should be renamed to something more appropriate.

**Comment by GAM3RG33K** [comment]
This issue is now resolved.

SimpleSettingsTile will take `child` widget as input to display on tap and an additional `onTap` callback.

Note: parameter name is changed from `screen` to `child`

**Comment by chapmacl** [comment]
The name change from `screen ` to `child` has not been updated on the Pub dev page, the API, the repo README, or the documentation within the code. I feel this issue includes updating these for consistency
