### ISSUE TITLE
SimpleSettingsTitle subtitle null check

### ISSUE THREAD

**Issue by blluv** [GAM3RG33K/flutter_settings_screens#71]
Issue #55  has not been resolved yet.

I think it should be fixed like this.
https://github.com/GAM3RG33K/flutter_settings_screens/blob/fd8f6389e6013431933df19b18a165afee73cc9a/lib/src/widgets/base_widgets.dart#L164-L170

to

```dart
 subtitle: widget.subtitle == null
     ? null 
     : Text( 
         widget.subtitle!, 
         style: 
             widget.subtitleTextStyle ?? subtitleTextStyle(context), 
       ), 
```

**Comment by GAM3RG33K** [comment]
@blluv  Hi, thanks for finding this out. If you don't mind can you just send me a PR with the fix?
