### ISSUE TITLE
Can I save simple list object on hive?

### ISSUE THREAD

**Issue by tohosys** [GAM3RG33K/flutter_settings_screens#73]
**Simple object**
`class User {`
  `    String name;`
  `    int age;`
  `    User({ this.name, this.age});`
`}`

**Test code**
`var u = User(name: 'k1', age: 30);`
`Settings.setValue<Object>('key-u', u, notify: true);`
`var x = Settings.getValue<Object>('key-u', null);`

**Error**
`
Unhandled Exception: HiveError: Cannot write, unknown type: User. Did you forget to register an adapter?
`
I don't know where to ask, so write question here. Thanks.

**Comment by GAM3RG33K** [comment]
Anything you want to store in the Hive DB must be serializable manually or should have implemented a `HiveAdapter` .

This link might help you get to know more about saving custom objects in Hive:
https://docs.hivedb.dev/#/custom-objects/type_adapters

Closing this issue, as it is not part of this library.
