### ISSUE TITLE
SimpleSettingsTile should take an optional `onTap` callback

### ISSUE THREAD

**Issue by GAM3RG33K** [GAM3RG33K/flutter_settings_screens#8]
an additional `onTap` call back would be good for situations like when dev needs to show a dialog/toast on tap of the setting instead of a whole another setting page.

**Comment by GAM3RG33K** [comment]
This feature is added in the last commit. a `VoidCallback` is added with name `onTap` for SimpleSettingsTile

**Comment by zanesc** [comment]
@GAM3RG33K will this commit be released to pub? I don't see the onTap callback in the latest 0.2.0+1 version. It is indeed a very useful feature to have. Thank you for your work.
