### ISSUE TITLE
0.3.2-null-safety complaints about unnecessary WidgetsBinding.instance? null check.

### ISSUE THREAD

**Issue by RoarGronmo** [GAM3RG33K/flutter_settings_screens#82]
Getting theese warnings: 
```
/C:/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_settings_screens-0.3.2-null-safety/lib/src/widgets/settings_widgets.dart:613:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/C:/Flutter/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance?.addPostFrameCallback((_) {
                   ^
DartUri: Unresolved uri: dart:web_sql
DartUri: Unresolved uri: dart:ui
```

Any hope for null safe release which addresses this particular problem ?

**Comment by laogao** [comment]
Maybe we could define and use some function such as `T? _ambiguate<T>(T? value) => value;` to wrap access to `WidgetsBinding.instance`, which treats values of both `T` and `T?` equally as `T?`. When everyone is on Flutter 3.0.0+, we can then drop it?

**Comment by tarun-netweb** [comment]
Same problem here:-

: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
../…/widgets/settings_widgets.dart:581
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../snap/flutter/common/flutter/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1
        WidgetsBinding.instance?.addPostFrameCallback((_) {

**Comment by GAM3RG33K** [comment]
@nyxkn Can you take a look at these issues generated by the latest flutter stable/beta sdk update? 
I am planning to resolve this maybe during this weekend or by the end of next week. 

If you can just the issues & provide a list of it here, we can connect over the weekend & get it done. I am sure it won't be a long list of changes for this.
