### ISSUE TITLE
Each Setting widget should have `subtitle` or `description` parameter

### ISSUE THREAD

**Issue by GAM3RG33K** [GAM3RG33K/flutter_settings_screens#9]
For example:
A switch based setting has too little space to show a full description in the title.

So, a description text can be added below the title, maybe replacing the subtitle, that has multiline text adjust within the tile.

**Comment by GAM3RG33K** [comment]
Now every settings widget with enough space, has a `substitle` property as well.

**Comment by ChangJoo-Park** [comment]
@GAM3RG33K There is no subtitle with your example.
